### ISSUE TITLE
Add greetings action

### ISSUE THREAD

**Issue by musavveer** [mexili/skribbl#14]
I would like to add a Github Action for greeting new contributors with :
- New PR
- New Issue
Do assign it to me @madhavrathi

**Comment by madhavrathi** [comment]
Sure, go ahead.
Thanks !!

**Comment by musavveer** [comment]
I will send a PR as earliest as possible.

**Comment by musavveer** [comment]
@madhavrathi Instead of GitHub actions we can use Welcome Bot.
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
For reference, check out: https://github.com/apps/welcome
