### ISSUE TITLE
Add Contributing.md file

### ISSUE THREAD

**Issue by KerinPithawala** [mexili/skribbl#4]
I think it is important to have contributing guidelines so that an open-source contributor know how to contribute properly.
Can I work on this?

**Comment by yashgautam9274** [comment]
I want to work on this issue

**Comment by madhavrathi** [comment]
Please go ahead. Assigning this issue to @Kerveyfelix as she mentioned it first. @yashgautam9274 Feel free to work on open issues or open your new ones as well. Cheers !!

**Comment by musavveer** [comment]
I would like to work on it.
Please assign it to me @madhavrathi
